//version constants for the Kotlin DSL dependencies
object Versions {
    const val kotlin = "1.5.21"
    const val gradle = "7.0.3"
    const val coreKtx = "1.7.0"
    const val appcompat = "1.4.0"
    const val material = "1.4.0"
    const val compose = "1.0.1"
    const val activityCompose = "1.4.0"
    const val lifecycleRuntimeKtx = "2.4.0"
    const val junit = "4.+"
    const val androidxJunit = "1.1.3"
    const val espressoCore = "3.4.0"
    const val retrofit = "2.9.0"
    const val gsonConverter = "2.5.0"
    const val room = "2.3.0"
    const val okhttp = "4.9.3"
    const val coroutines = "1.3.9"
    const val coil = "1.4.0"
    const val koin = "3.1.4"
    const val accompanist = "0.22.0-rc"
}